export {default as Home} from './Home'
export {default as Self} from './Self'
export {default as Skills} from './Skills'
export {default as Learning} from './Learning'
export {default as Contact} from './Contact'
export {default as Navbar} from './Navbar'
export {default as Title} from './Title'